import React from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { Cpu, TrendingUp, Clock, CheckCircle2 } from 'lucide-react';

export const AnalyticsCharts = ({ analyticsData }) => {
  if (!analyticsData) return null;

  const { summary, hourlyDistribution, mlMetrics } = analyticsData;

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '24px', marginTop: '24px' }}>
      {/* Peak Hours Hourly Distribution Bar Chart */}
      <div className="glass-panel" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
          <div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>Peak Hours Distribution</h3>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Tokens generated by time of day</p>
          </div>
          <Clock color="var(--accent-cyan)" size={20} />
        </div>

        <div style={{ height: '220px', width: '100%' }}>
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={hourlyDistribution}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
              <XAxis dataKey="hour" stroke="#64748b" fontSize={11} />
              <YAxis stroke="#64748b" fontSize={11} />
              <Tooltip contentStyle={{ background: '#131b2e', border: '1px solid #334155', borderRadius: '8px', color: '#fff' }} />
              <Bar dataKey="tokens" fill="url(#barGradient)" radius={[4, 4, 0, 0]} />
              <defs>
                <linearGradient id="barGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#06b6d4" />
                  <stop offset="100%" stopColor="#3b82f6" />
                </linearGradient>
              </defs>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* ML Prediction Performance Analytics */}
      <div className="glass-panel" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
          <div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>AI Prediction Performance</h3>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Live model evaluation metrics</p>
          </div>
          <Cpu color="var(--accent-indigo)" size={20} />
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
          <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border-light)' }}>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>MAE (Error)</span>
            <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--accent-emerald)' }}>
              {mlMetrics?.maeMinutes || 2.1} <span style={{ fontSize: '0.8rem' }}>mins</span>
            </div>
          </div>
          <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border-light)' }}>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>$R^2$ Accuracy</span>
            <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--accent-cyan)' }}>
              {mlMetrics?.r2Score || 0.91}
            </div>
          </div>
        </div>

        <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.8' }}>
          <div><strong>Active Model:</strong> {mlMetrics?.modelName || 'Random Forest Regressor'}</div>
          <div><strong>Completion Rate:</strong> {summary?.completionRatePercentage}%</div>
          <div><strong>Average Wait Time:</strong> {summary?.avgWaitMinutes} mins</div>
        </div>
      </div>
    </div>
  );
};
